[package]
name = "ramd-vm-runtime"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = ""

[dependencies]
ramd-db.workspace = true
ramd-vm.workspace = true

eyre.workspace = true
tracing.workspace = true
